name: scriping
recipe: lamp
config:
  php: '7.4'
  webroot: .
#   database: mysql:8.0
#   xdebug: true
#   ssl: true
  proxy:
    appserver:
      - web.ci.lndo.site
#     database:
#       - db.ci.lndo.site
#     mailhog:
#       - mail.ci.lndo.site
    pma:
#       - pma.ci.lndo.site
    node:
      - node.ci.lndo.site
services:
  node:
    type: node:custom
    overrides:
        build: ./docker
        image: tonipasqual/popcustom
        environment:
            env: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  database:
    type: mysql:8.0
    portforward: 3306
    creds:
      user: lamp
      password: lamp
      database: lamp
    authentication: caching_sha2_password
#   mailhog:
#     type: mailhog
#     hogfrom:
#       - appserver
#     portforward: 1026
#   pma:
#     type: phpmyadmin
#     hosts: database
#   node:
#     type: node
#     build:
#       - npm install
#       - npm install servor -g
tooling:
  npm:
    service: node
  npx:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  servor:
    service: node